name: Init

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  general:
    name: General
    runs-on: ubuntu-24.04
    steps:
      name: Run
      run: |
        echo ${{ github.sha }}
